apiVersion: v1 
kind: PersistentVolume
metadata:
  name: manual-fs-vol 
spec:
  capacity:
    storage: 1Ti
  nfs:
    path: /vol01
    server: 10.144.200.122
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: manual-fs-vol-claim