apiVersion: v1 
kind: LimitRange
metadata: 
  name: dev-team-limit-range 
  namespace: dev-team 
spec:
  limits:
  - type: Pod
    min:  # request
      cpu: "100m"
      memory: "100Mi"
    max: # limit
      cpu: "150m"
      memory: "150Mi"