apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-team-ns-quota 
  namespace: dev-team 
spec:
  hard:
    requests.cpu: "1"     #minimum
    requests.memory: "1Gi"
    limits.cpu: "2"       #maxmium
    limits.memory: "2Gi"
    pods: "10"