apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: dynamic-disk-vol-claim 
spec: 
  resources:
    requests:
      storage: 5Gi 
  accessModes:
    - ReadWriteOnce
  storageClassName: standard