apiVersion: batch/v1
kind: CronJob
metadata:
  name: print-hello-job 
spec:
  schedule: "* * * * *"  #every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh 
            - -c 
            - echo "Hello, NextOps"
          restartPolicy: OnFailure