apiVersion: monitoring.coreos.com/v1 
kind: ServiceMonitor
metadata:
  name: mongodb-exporter-sm 
  labels:
    release: k8s-prom-stack
spec:
  selector:
    matchLabels:  
      app: mongodb-exporter
  endpoints:
  - port: metrics  
    interval: 30s