apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
      - name: nginx-prod
        image: nginx        
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-vol
          mountPath: /etc/nginx/conf.d/     #/etc/nginx/conf.d/default.conf
      volumes:
      - name: nginx-config-vol
        configMap:
          name: nginx-config-cm #default.conf