apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: dyn-fs-vol-claim
spec:
  resources:
    requests:
      storage: 1Ti
  accessModes:
    - ReadWriteMany
  storageClassName: custom-fs-sc  