---
apiVersion: apps/v1 
kind: Deployment  #Controller
metadata:
  name: nginx-lb-deploy
  labels:
    app: nginx-lb
    env: prod
spec: 
  replicas: 8
  selector:
    matchLabels:
      app: nginx-lb
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-lb
        location: eastus
    spec:
      containers:
        - name: nginx 
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1 
kind: Service
metadata:
  name: nginx-lb-service
  labels:
    app: nginx-lb
spec:
  selector:
    app: nginx-lb
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer