---
apiVersion: apps/v1 
kind: Deployment  #Controller
metadata:
  name: httpd-deploy
  labels:
    app: httpd
spec: 
  replicas: 6
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      name: httpd-pod
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd 
          image: httpd:latest
          ports:
            - containerPort: 80  
---
apiVersion: v1 
kind: Service 
metadata:
  name: httpd-service 
  labels:
    app: httpd 
spec:
  selector:
    app: httpd
  ports:
  - port: 80
    targetPort: 80
  type: NodePort #it uses node's public ip and a random port after 30000 on any node.